# Generated by Django 5.0.2 on 2024-03-05 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activation_code',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
